### ISSUE TITLE
stopped working in KB 1.0.22

### ISSUE THREAD

**Issue by thob** [BlueTeck/kanboard_plugin_overwrite_translation#2]
I get 500 once I copy it into the plugin dir

Update: was the Namespace issue. Still now i don't get the translations.

**Comment by TimoStahl** [comment]
I will check it in the next days.

**Comment by TimoStahl** [comment]
Could you please try to change 

Overwrite_translation/Plugin.php
Line 12

into 

$this->on('app.bootstrap', function($container) {

Or just redownload the git.

Please give me some feedback.

**Comment by thob** [comment]
looking good from here. Thanx
